### PR TITLE
Csv issues

### LINKED ISSUE #195: CSV Ingest/error handling
Sometimes when a CSV has extra rows or columns, the whole post process will not work instead of just omitting the bad data. 

The error is almost always `Error transforming ES for photographs: no implicit conversion of nil into String`

In order to fix this I manually go in and delete extra rows and sometimes have to delete errant notes that are outside the set up column structure

I think Datura needs to: 

- ignore any column that doesn't match a defined field
- ignore any row that does not have an ID at minimum (maybe ID and title)

Also see https://github.com/CDRH/teaa/issues/81

### PR DESCRIPTION
**Pull request by wkdewey**
Will fix #195 

Note that I am still testing it with PSFP, PfF, and other repos

### CODE REVIEW

File: lib/datura/file_types/file_csv.rb [hunk 1]
```diff
@@ -36,10 +36,11 @@ def read_csv(file_location, encoding="utf-8")
     CSV.read(file_location, **{
       encoding: encoding,
       headers: true,
-      return_headers: true
-    })
+      return_headers: true,
+      :header_converters=> lambda {|f| f.strip},
+    :converters=> lambda {|f| f ? f.strip : nil}
+      })
```
Comment (techgique) [inline lib/datura/file_types/file_csv.rb:42]: Couple questions here:

- From reviewing docs it looks like enabling `return_headers` is essentially undoing what `headers: true` does, unless you are using the `.headers` method on the CSV object which returns `nil` unless `headers: true` is present in options. If we're not using the `.headers` method, I think we can just remove both the `headers: true` and `return_headers: true` options.
- The converters lines present style questions:
  - Firstly, the second converters line's indentation doesn't match the other options lines. And I think the closing `})` should be unindented to match the indentation of the `CSV.read(...` line.
  - Also, can these be written as `header_converters: lambda ...` and `converters: lambda ...` to match the other options syntax? Options keys are symbols so we shouldn't need the older, more verbose hash rocket syntax and the Ruby style guide dictates not mixing syntax styles as well.

**Review by techgique — CHANGES_REQUESTED** [review]

File: lib/datura/file_types/file_csv.rb (hunk 1 above)
Comment (wkdewey) [reply lib/datura/file_types/file_csv.rb:42]: We do use `.headers` on the csv object in several places and the code has always had both `headers` and `return_headers` since Jessica initially wrote this method.(https://github.com/CDRH/datura/blame/dev/lib/datura/file_types/file_csv.rb). I'm afraid if we change it it will break.
I can change the other lines though.

Comment (wkdewey) [reply lib/datura/file_types/file_csv.rb:42]: see here: https://ruby-doc.org/3.1.6/stdlibs/csv/CSV.html#class-CSV-label-Option+headers and I think the rest of the code accounts for the header row. it could theoretically be refactored (omit return_headers, and don't skip the header in loops) but it's not currently broken.

Comment (techgique) [reply lib/datura/file_types/file_csv.rb]: Ah okay. If it would require a larger refactor to deal with use of `.headers` etc that's definitely out of scope of this PR. I made an issue for us to potentially revisit that later though: https://github.com/CDRH/datura/issues/246

**Comment by wkdewey** [comment]
I believe that issue is completed (and that previous updates changed the behavior that Karin described)
